In [2]:
import pandas as pd
import os
import numpy as np
import pickle as pkl

import matplotlib.pyplot as plt

In [18]:
def parse_version(version_str):
    version = version_str.split('.')[1:]
    return tuple(map(int, version))

In [19]:
results = np.sort(os.listdir('../results'))
results = [x for x in results if not x.endswith('.csv')]
results = sorted(results, key=lambda x: parse_version(x))
results = ['../results/'+x+'/results.pkl' for x in results]
results

['../results/2024.1.0/results.pkl',
 '../results/2024.1.1/results.pkl',
 '../results/2024.2.0/results.pkl',
 '../results/2024.2.1/results.pkl',
 '../results/2024.3.0/results.pkl',
 '../results/2024.3.1/results.pkl',
 '../results/2024.4.0/results.pkl',
 '../results/2024.4.1/results.pkl',
 '../results/2024.4.2/results.pkl',
 '../results/2024.5.0/results.pkl',
 '../results/2024.5.1/results.pkl',
 '../results/2024.5.2/results.pkl',
 '../results/2024.6.0/results.pkl',
 '../results/2024.6.1/results.pkl',
 '../results/2024.6.2/results.pkl',
 '../results/2024.7.0/results.pkl',
 '../results/2024.7.1/results.pkl',
 '../results/2024.8.0/results.pkl',
 '../results/2024.8.1/results.pkl',
 '../results/2024.8.2/results.pkl',
 '../results/2024.9.0/results.pkl',
 '../results/2024.9.1/results.pkl',
 '../results/2024.10.0/results.pkl',
 '../results/2024.11.1/results.pkl',
 '../results/2024.11.2/results.pkl',
 '../results/2024.12.0/results.pkl']

In [20]:
dask_versions = []
ram_sizes = []
ram_cols = ['baron_8K_pancreas_rnaseq.zarr', 'hca_783K_blood_rnaseq.zarr', 'saunders_110K_brain_rnaseq.zarr', 'tenx_1.3M_brain_rnaseq.zarr', 'zheng_69K_pbmc_rnaseq.zarr']
for result in results:
    with open(result, 'rb') as f:
        res = pkl.load(f)
    dask_versions.append(res['das_version'])
    ram_sizes.append([np.max(res[x]['ram']) for x in ram_cols])

In [21]:
df = {'dask_version': dask_versions}
for i, col in enumerate(ram_cols):
    df[col] = [x[i] for x in ram_sizes]
df = pd.DataFrame(df)
df

,dask_version,baron_8K_pancreas_rnaseq.zarr,hca_783K_blood_rnaseq.zarr,saunders_110K_brain_rnaseq.zarr,tenx_1.3M_brain_rnaseq.zarr,zheng_69K_pbmc_rnaseq.zarr
0,2024.1.0,271.558594,664.796875,618.882812,765.160156,572.496094
1,2024.1.1,250.527344,677.792969,628.582031,760.425781,563.511719
2,2024.2.0,317.597656,666.269531,603.820312,768.312500,655.832031
3,2024.2.1,276.710938,651.355469,643.464844,770.601562,613.566406
4,2024.3.0,299.781250,685.765625,604.128906,773.003906,576.003906
5,2024.3.1,271.250000,665.824219,624.921875,787.550781,639.398438
6,2024.4.0,322.187500,696.933594,641.558594,763.582031,625.601562
7,2024.4.1,268.457031,693.132812,629.863281,775.195312,619.625000
8,2024.4.2,277.066406,683.250000,594.152344,736.605469,591.253906
9,2024.5.0,255.738281,674.628906,643.906250,775.136719,639.222656
10,2024.5.1,302.109375,692.015625,628.058594,728.003906,568.984375
11,2024.5.2,316.585938,676.792969,622.832031,767.648438,591.558594
12,2024.6.0,290.566406,681.906250,614.898438,764.562500,611.359375
13,2024.6.1,265.265625,695.750000,608.535156,780.566406,614.085938
14,2024.6.2,271.109375,681.777344,623.414062,781.386719,581.976562
15,2024.7.0,299.167969,714.160156,603.867188,751.472656,600.929688
16,2024.7.1,282.925781,661.519531,590.160156,721.503906,619.132812
17,2024.8.0,391.789062,9605.253906,5980.398438,36086.023438,3593.652344
18,2024.8.1,404.417969,12292.554688,5506.449219,34362.855469,2607.617188
19,2024.8.2,369.113281,11830.074219,8463.734375,34108.710938,3482.625000
20,2024.9.0,455.355469,11318.917969,6550.246094,35648.382812,3782.148438
21,2024.9.1,369.246094,11453.675781,5907.320312,35755.296875,4381.921875
22,2024.10.0,389.691406,11810.761719,5197.070312,34269.035156,2683.089844
23,2024.11.1,334.933594,11494.699219,5140.140625,34306.558594,19618.035156
24,2024.11.2,355.585938,11857.617188,5932.324219,36206.410156,6208.671875
25,2024.12.0,399.453125,11767.593750,5621.160156,34948.914062,3964.804688

In [22]:
# Zarr: 2.16

In [23]:
df_sort = df.sort_values(by=['tenx_1.3M_brain_rnaseq.zarr'])
df_sort

,dask_version,baron_8K_pancreas_rnaseq.zarr,hca_783K_blood_rnaseq.zarr,saunders_110K_brain_rnaseq.zarr,tenx_1.3M_brain_rnaseq.zarr,zheng_69K_pbmc_rnaseq.zarr
16,2024.7.1,282.925781,661.519531,590.160156,721.503906,619.132812
10,2024.5.1,302.109375,692.015625,628.058594,728.003906,568.984375
8,2024.4.2,277.066406,683.250000,594.152344,736.605469,591.253906
15,2024.7.0,299.167969,714.160156,603.867188,751.472656,600.929688
1,2024.1.1,250.527344,677.792969,628.582031,760.425781,563.511719
6,2024.4.0,322.187500,696.933594,641.558594,763.582031,625.601562
12,2024.6.0,290.566406,681.906250,614.898438,764.562500,611.359375
0,2024.1.0,271.558594,664.796875,618.882812,765.160156,572.496094
11,2024.5.2,316.585938,676.792969,622.832031,767.648438,591.558594
2,2024.2.0,317.597656,666.269531,603.820312,768.312500,655.832031
3,2024.2.1,276.710938,651.355469,643.464844,770.601562,613.566406
4,2024.3.0,299.781250,685.765625,604.128906,773.003906,576.003906
9,2024.5.0,255.738281,674.628906,643.906250,775.136719,639.222656
7,2024.4.1,268.457031,693.132812,629.863281,775.195312,619.625000
13,2024.6.1,265.265625,695.750000,608.535156,780.566406,614.085938
14,2024.6.2,271.109375,681.777344,623.414062,781.386719,581.976562
5,2024.3.1,271.250000,665.824219,624.921875,787.550781,639.398438
19,2024.8.2,369.113281,11830.074219,8463.734375,34108.710938,3482.625000
22,2024.10.0,389.691406,11810.761719,5197.070312,34269.035156,2683.089844
23,2024.11.1,334.933594,11494.699219,5140.140625,34306.558594,19618.035156
18,2024.8.1,404.417969,12292.554688,5506.449219,34362.855469,2607.617188
25,2024.12.0,399.453125,11767.593750,5621.160156,34948.914062,3964.804688
20,2024.9.0,455.355469,11318.917969,6550.246094,35648.382812,3782.148438
21,2024.9.1,369.246094,11453.675781,5907.320312,35755.296875,4381.921875
17,2024.8.0,391.789062,9605.253906,5980.398438,36086.023438,3593.652344
24,2024.11.2,355.585938,11857.617188,5932.324219,36206.410156,6208.671875

In [25]:
df_sort[df_sort['tenx_1.3M_brain_rnaseq.zarr']<800].sort_values(by='dask_version')

,dask_version,baron_8K_pancreas_rnaseq.zarr,hca_783K_blood_rnaseq.zarr,saunders_110K_brain_rnaseq.zarr,tenx_1.3M_brain_rnaseq.zarr,zheng_69K_pbmc_rnaseq.zarr
0,2024.1.0,271.558594,664.796875,618.882812,765.160156,572.496094
1,2024.1.1,250.527344,677.792969,628.582031,760.425781,563.511719
2,2024.2.0,317.597656,666.269531,603.820312,768.312500,655.832031
3,2024.2.1,276.710938,651.355469,643.464844,770.601562,613.566406
4,2024.3.0,299.781250,685.765625,604.128906,773.003906,576.003906
5,2024.3.1,271.250000,665.824219,624.921875,787.550781,639.398438
6,2024.4.0,322.187500,696.933594,641.558594,763.582031,625.601562
7,2024.4.1,268.457031,693.132812,629.863281,775.195312,619.625000
8,2024.4.2,277.066406,683.250000,594.152344,736.605469,591.253906
9,2024.5.0,255.738281,674.628906,643.906250,775.136719,639.222656
10,2024.5.1,302.109375,692.015625,628.058594,728.003906,568.984375
11,2024.5.2,316.585938,676.792969,622.832031,767.648438,591.558594
12,2024.6.0,290.566406,681.906250,614.898438,764.562500,611.359375
13,2024.6.1,265.265625,695.750000,608.535156,780.566406,614.085938
14,2024.6.2,271.109375,681.777344,623.414062,781.386719,581.976562
15,2024.7.0,299.167969,714.160156,603.867188,751.472656,600.929688
16,2024.7.1,282.925781,661.519531,590.160156,721.503906,619.132812

In [26]:
df.to_csv('../results/results.csv', index=False)

# Plots

In [23]:
for result in results:
    with open(result, 'rb') as f:
        res = pkl.load(f)
    print(res['das_version'])
    os.makedirs('../plots/'+res['das_version'], exist_ok=True)
    for col in ram_cols:
        print(col)
        plt.plot(res[col]['ram'])
        plt.title(col)
        plt.xlabel('Time (s)')
        plt.ylabel('RAM (MB)')
        plt.savefig('../plots/'+res['das_version']+'/'+col+'.png')
        plt.close()
    print()
    print()

2024.9.1
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.8.2
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.5.1
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.1.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.2.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.1.1
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.9.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.7.1
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.7.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.8.1
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.5.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.6.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.4.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.10.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.11.2
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.6.1
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.12.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.4.1
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.3.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.2.1
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.5.2
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.4.2
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.8.0
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.3.1
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.6.2
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr


2024.11.1
baron_8K_pancreas_rnaseq.zarr
hca_783K_blood_rnaseq.zarr
saunders_110K_brain_rnaseq.zarr
tenx_1.3M_brain_rnaseq.zarr
zheng_69K_pbmc_rnaseq.zarr